title: Hailey Willis
description:

url: http://haileywillis.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: wesleywillis
   twitter: weswilliscodes
  #  facebook: 
   email: brimaidesigns@gmail.com

# google_analytics:
